from _typeshed import Incomplete
from mpesakit.auth import AsyncTokenManager, TokenManager
from mpesakit.http_client import AsyncHttpClient, HttpClient
from mpesakit.imsi import (
    IMSIV1Response,
    IMSIV2Response,
    IMSIV3Response,
)

class IMSIService:
    http_client = Incomplete
    token_manager = Incomplete
    def __init__(self,http_client: HttpClient,token_manager: TokenManager) ->None: ...
    def query_v1(self,customer_number: str) -> IMSIV1Response: ...
    def query_v2(self,customer_number: str) -> IMSIV2Response: ...
    def query_v3(self,customer_number: str) -> IMSIV3Response: ...

class AsyncIMSIService:
    http_client = Incomplete
    token_manager = Incomplete
    def __init__(self,http_client: HttpClient,token_manager: TokenManager) ->None: ...
    async def query_v1(self,customer_number: str) -> IMSIV1Response: ...
    async def query_v2(self,customer_number: str) -> IMSIV2Response: ...
    async def query_v3(self,customer_number: str) -> IMSIV3Response: ...
    